import React from 'react';

export const metadata = {
    title: "About |Exporting Next JS",
    description: "Generated by create next app",
  };

const aboutPage = () => {
    return (
        <div>
            <h1>This is About Page</h1>
        </div>
    );
};

export default aboutPage;