import React from "react";
import { Anek_Devanagari } from "next/font/google";
import Image from "next/image";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";

const anek = Anek_Devanagari({weight: ['400' , '500' , '700'], subsets: ['latin']})

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const getTime = async () => {
  const session = await getServerSession(authOptions);
  console.log("🚀 ~ getTime ~ session:", {session})
  
  const res = await fetch('http://localhost:3000/time' , { next: {revalidate : 5} });
  const data = await res.json();
  return data.currentTime;
};

const contactPage = async () => {
  const currentTime = await getTime();
  console.log('currentTime' , currentTime);
  return (
    <div>
      <h1 className={`${anek.className} font-bold text-3xl`}>This is Contact Page</h1>

      <Image src='https://images.unsplash.com/photo-1720048170970-3848514c3d60?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' alt="" width={500} height={500} placeholder = 'empty' quality={75} loading = 'lazy'  />
      <br />
        <p className="text-rose-500">Time: {currentTime}</p>
    </div>
  );
};

export default contactPage;
