import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Exporting Next JS",
    template: "%s | Exporting Next JS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <div className="min-h-screen p-10">{children}</div>
        <footer className="px-5 py-4 bg-amber-500">
          <p className="text-center">This is a footer</p>
        </footer>
      </body>
    </html>
  );
}
